name: Publishing ~ ciphering

on:
  release:
    types: [created]

jobs:
  build:
    name: Building package 🪛
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: ci
      - run: npm run test

  publish-npm:
    needs: build
    name: Deploying package to npm 😱
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Continious Integration 🪛
        run: npm ci

      - name: Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}